### ISSUE TITLE
Let relative file paths be resolved based on directory nmo.jar is in

### ISSUE THREAD

**Issue by Qqwy** [PolyphasicDevTeam/NoMoreOversleeps#1]
Currently, file paths, like the ones used for the noise files, can either be absolute or relative.

However, relative file paths (at least on Linux, that is), are resolved with your home folder (`/home/yourusername`) as base path, rather than the actual location `nmo.jar` exists in:

[Nomoreoversleeps-0.log](https://github.com/PolyphasicDevTeam/NoMoreOversleeps/files/1399953/Nomoreoversleeps-0.log)

(config file: https://gist.github.com/Qqwy/f5db5abc94acba3e186835207fc0a677)

**Comment by Tinytimrob** [comment]
Should be fixed in next release
