### ISSUE TITLE
Show time until next nap in local client interface

### ISSUE THREAD

**Issue by Qqwy** [PolyphasicDevTeam/NoMoreOversleeps#2]
One of the main things I'd like to see in the local client interface (Possibly in the 'monitoring control' section?), is a countdown-timer of how long it takes before the next nap will start, for two reasons:

1. it makes it easy to check if the app is configured properly, and the alarms/reminders will sound at the proper times.
2. The couple of hours after a missed nap and midnight core are EXTREMELY hard to keep awake in. Being able to count them down (even when your mental state is very unfocused) would be really nice.

:slightly_smiling_face:

**Comment by Tinytimrob** [comment]
Good idea, I'll look into adding this

**Comment by Qqwy** [comment]
This works very well. I think this issue can be closed, since it has been incorporated in v0.12 :heart_eyes: .
